bencekiss/config/routes.rb
Rails.application.routes.draw do


  root "bences#show"

  resources :bences, only: %i(show edit update) do
    resources :edus
    resources :works
    resources :projects
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bencekiss/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bencekiss/app/models/bence.rb
class Bence < ApplicationRecord
  has_many :edus
  has_many :works
  has_many :projects

  # accepts_nested_attributes_for :edus, reject_if: :all_blank, allow_destroy: true
  # accepts_nested_attributes_for :works, reject_if: :all_blank, allow_destroy: true
  # accepts_nested_attributes_for :projects, reject_if: :all_blank, allow_destroy: true

end

bencekiss/app/models/edu.rb
class Edu < ApplicationRecord
  belongs_to :bence
end

bencekiss/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :bence
end

bencekiss/app/models/work.rb
class Work < ApplicationRecord
  belongs_to :bence
end

bencekiss/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

bencekiss/app/controllers/bences_controller.rb
class BencesController < ApplicationController
  def edit
    @bence = Bence.first
  end

  def update
    @bence = Bence.first
    if @bence.update_attributes(bence_params)
      flash[:notice] = "Updated info"
      redirect_to root_path
    else
      flash.now[:notice] = "something went wrong, check whats going on"
      render :new
    end
  end

  def show
  
    @bence = Bence.first

  end

  private
  def bence_params
    params.require(:bence).permit(:description, :email, :name, :phone)
  end
end

bencekiss/app/controllers/edus_controller.rb
class EdusController < ApplicationController
  def index
    @edus = Edu.all
  end

  def new
    @edu = Edu.new
  end

  def create
    @edu = Edu.new(edu_params)
    @edu.bence_id = 1
    if @edu.save
      flash[:notice] = "Education added"
      redirect_to root_path
    else
      flash.now[:notice] = "something went wrong, check whats going on"
      render :new
    end
  end

  def edit
    @edu = Edu.find(params[:id])
  end

  def update
    @edu = Edu.find(params[:id])
    if @edu.update_attributes(edu_params)
      flash[:notice] = "Education updated"
      redirect_to root_path
    else
      flash.now[:notice] = "something went wrong, check whats going on"
      render :edit
    end
  end

  def destroy
    @edu = Edu.find(params[:id])
    @edu.destroy
    redirect_to root_path
  end

  private
  def edu_params
    params.require(:edu).permit(:name, :location, :school, :start_date, :end_date, :description)
  end
end

bencekiss/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.bence_id = 1
    if @project.save
      flash[:notice] = "Project added"
      redirect_to root_path
    else
      flash.now[:notice] = "something went wrong, check whats going on"
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:notice] = "Project added"
      redirect_to root_path
    else
      flash.now[:notice] = "something went wrong, check whats going on"
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :url, :bence_id)
  end
end

bencekiss/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    @work.bence_id = 1
    if @work.save
      flash[:notice] = "Work added"
      redirect_to root_path
    else
      flash.now[:notice] = "something went wrong, check whats going on"
      render :new
    end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update_attributes(work_params)
      flash[:notice] = "Work updated"
      redirect_to root_path
    else
      flash.now[:notice] = "something went wrong, check whats going on"
      render :new
    end
  end

  def destroy
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to root_path
  end

  private
  def work_params
    params.require(:work).permit(:name, :description, :location, :start_date, :end_date)
  end
end

bencekiss/app/helpers/application_helper.rb
module ApplicationHelper
end

bencekiss/app/helpers/bence_helper.rb
module BenceHelper
end

bencekiss/app/helpers/edus_helper.rb
module EdusHelper
end

bencekiss/app/helpers/projects_helper.rb
module ProjectsHelper
end

bencekiss/app/helpers/works_helper.rb
module WorksHelper
end

bencekiss/app/views/bence/edit.html.erb
<h1>Bence#edit</h1>
<%= form_for @bence do |f| %>
  <div class="fields">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="fields">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="fields">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="fields">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="action">
    <%= f.submit "Update" %>
  </div>
<% end %>

bencekiss/app/views/bences/edit.html.erb
<h1>Bence#edit</h1>
<%= form_for @bence do |f| %>
  <div class="fields">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="fields">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="fields">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="fields">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="action">
    <%= f.submit "Update" %>
  </div>
<% end %>

bencekiss/app/views/bences/show.html.erb
<!-- <div class="headlines">
  <h1><%# @bence.name %></h1>
</div> -->
<div class="description">
  <%= @bence.description %>
  <div class="profile-mods">
    <%= link_to "Edit profile", edit_bence_path(1) %>
  </div>
</div>

bencekiss/app/views/edus/_form.html.erb
<%= form_for [Bence.first, @edu] do |f| %>
  <div class="fields">
    <%= f.label :name, value: "Title" %>
    <%= f.text_field :name %>
  </div>
  <div class="fields">
    <%= f.label :school %>
    <%= f.text_field :school %>
  </div>
  <div class="fields">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="fields">
    <%= f.label :start_date, value: "Start year" %>
    <%= f.text_field :start_date %>
  </div>
  <div class="fields">
    <%= f.label :end_date, value: "End year" %>
    <%= f.text_field :end_date %>
  </div>
  <div class="fields">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

bencekiss/app/views/edus/edit.html.erb
<h1>Edus#edit</h1>
<%= render 'form' %>

bencekiss/app/views/edus/index.html.erb
<h1>Edus#index</h1>
<p>
  <%= link_to "New Education", new_bence_edu_path(Bence.first) %>
</p>
<div class="educations">
  <% @edus.each do |education| %>
    <div class="education">
      <div class="edu-name">
        <%= education.name %>
      </div>
      <div class="edu-school">
        <%= education.school %>, <%= education.location %>
      </div>
      <div class="edu-years">
        <%= education.start_date %> - <%= education.end_date %>
      </div>
      <div class="edu-description">
        <%= education.description %>
      </div>
    </div>

    <p>
      <%= link_to "Edit education", edit_bence_edu_path(Bence.first, education.id) %>
    </p>
  <% end %>
</div>

bencekiss/app/views/edus/new.html.erb
<h1>New Education</h1>
<%= render 'form' %>

bencekiss/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bencekiss</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="navbar">
        <ul class="navlist">
          <li class="navelem">
            <%= link_to "Home", root_path %>
          </li>
          <li class="navelem">
            <%= link_to "Education", bence_edus_path(Bence.first) %>
          </li>
          <li class="navelem">
            <%= link_to "Works", bence_works_path(Bence.first) %>
          </li>
          <li class="navelem">
            <%= link_to "Projects", bence_projects_path(Bence.first) %>
          </li>
        </ul>
      </nav>
    </header>

    <main>
      <%= image_tag "https://s3.us-east-2.amazonaws.com/bencekissfirst/resume/background_2.png" %>
      <div class="flashes">
        <% if flash[:notice] %>
          <p id="notice"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:alert] %>
          <p id="alert"><%= flash[:alert] %></p>
        <% end %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <ul class="footerlist">
        <li class="footerelement"><%= Bence.first.email %></li>
        <li class="footerelement"><%= Bence.first.phone %></li>
      </ul>
    </footer>
  </body>
</html>

bencekiss/app/views/projects/_form.html.erb
<%= form_for [Bence.first, @project] do |f| %>
  <div class="fields">
    <%= f.label :name, value: "Title" %>
    <%= f.text_field :name %>
  </div>
  <div class="fields">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="fields">
    <%= f.label :url, value: "Project's website" %>
    <%= f.text_field :url %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

bencekiss/app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<%= render 'form' %>

bencekiss/app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>
  <%= link_to "New Project", new_bence_project_path(Bence.first) %>
</p>
<div class="projects">
  <% @projects.each do |project| %>
    <div class="project">
      <div class="project-name">
        <%= project.name %>
      </div>
      <div class="project-url">
        <%= link_to "#{project.url}", project.url %>
      </div>
      <div class="project-description">
        <%= project.description %>
      </div>
    </div>
    <p>
      <%= link_to "Edit Project", edit_bence_project_path(Bence.first, project) %>
    </p>
  <% end %>

</div>

bencekiss/app/views/projects/new.html.erb
<h1>Projects#new</h1>
<%= render 'form' %>

bencekiss/app/views/works/_form.html.erb
<%= form_for [Bence.first, @work] do |f| %>
  <div class="fields">
    <%= f.label :name, value: "Title" %>
    <%= f.text_field :name %>
  </div>
  <div class="fields">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>
  <div class="fields">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="fields">
    <%= f.label :start_date, value: "Start year" %>
    <%= f.text_field :start_date %>
  </div>
  <div class="fields">
    <%= f.label :end_date, value: "End year" %>
    <%= f.text_field :end_date %>
  </div>
  <div class="fields">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

bencekiss/app/views/works/edit.html.erb
<h1>Works#edit</h1>
<%= render 'form' %>

bencekiss/app/views/works/index.html.erb
<h1>Works#index</h1>
<p>
  <%= link_to "New Work Experience", new_bence_work_path(Bence.first) %>
</p>
<div class="works">
  <% @works.each do |work| %>
    <div class="work">
      <div class="work-name">
        <%= work.name %>
      </div>
      <div class="work-company">
        <%= work.company %>
      </div>
      <div class="work-location">
        <%= work.location %>, <%= work.start_date %> - <%= work.end_date %>
      </div>
      <div class="work-description">
        <%= work.description %>
      </div>
    </div>
    <p>
      <%= link_to "Edit Experience", edit_bence_work_path(Bence.first, work) %>
    </p>
  <% end %>
</div>

bencekiss/app/views/works/new.html.erb
<h1>Works#new</h1>
<%= render 'form' %>